import type { JelentkezesSzovegPaket } from './epit'

const hibak = {
  kotelezo: 'Dieses Feld ist erforderlich.',
  valasztas: 'Bitte wählen Sie eine Option.',
  legalabbEgy: 'Bitte wählen Sie mindestens eine Option.',
  egyeb: 'Bitte beschreiben Sie Ihre Antwort „Sonstiges“.',
  fajl: 'Das Hochladen eines Dokuments ist erforderlich.',
  email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
  tizennyolcEv: 'Für die Bewerbung müssen Sie mindestens 18 Jahre alt sein.',
  adatvedelem: 'Die Datenschutzerklärung muss akzeptiert werden.',
  hozzajarulas: 'Die Einwilligung ist erforderlich.',
  fajlPdf: 'Nur PDF-Format ist erlaubt.',
  fajlKep: 'Nur Bilddateien (JPG, PNG, WebP) sind erlaubt.',
  fajlKepVagyPdf: 'Nur Bild (JPG, PNG, WebP) oder PDF ist erlaubt.',
  profilkepFeldolgozas: 'Die Profilbild-Verarbeitung ist fehlgeschlagen.',
  kuldesSikertelen: 'Die Bewerbung konnte nicht gesendet werden. Bitte erneut versuchen.',
}

export const nemetJelentkezesPaket: JelentkezesSzovegPaket = {
  seo: {
    cim: 'Fahrerbewerbung | Juliette Logistique',
    leiras:
      'Bewerben Sie sich als Premium-Fahrzeugüberführer bei Juliette Logistique in Deutschland.',
    kulcsszavak: 'Fahrerbewerbung, Juliette Logistique, Karriere, Deutschland',
  },
  foCim: 'Bewerbungsformular für Fahrer',
  alcim: 'Premium- und Luxusfahrzeugführer in Deutschland',
  bevezeto:
    'Bitte füllen Sie das Formular so genau wie möglich aus. Die angegebenen Daten und Dokumente können im Auswahlprozess überprüft werden.',
  szekcio: {
    szemelyes: '1. Persönliche Daten',
    vezetes: '2. Fahrerfahrung',
    premium: '3. Premium- und Luxusfahrzeug-Erfahrung',
    nemetorszag: '4. Arbeit in Deutschland',
    jogositvany: '5. Führerschein und Fahrvorgeschichte',
    nyelv: '6. Sprachkenntnisse',
    keszsegek: '7. Erforderliche Fähigkeiten',
    feltetelek: '8. Arbeitsbedingungen',
    szurok: '9. Wichtige Auswahlfragen',
    dokumentumok: '10. Dokumente hochladen',
    motivacio: '11. Motivation',
    kuldes: '12. Bewerbung absenden',
  },
  mezo: {
    teljesNev: 'Vollständiger Name',
    szuletesiDatum: 'Geburtsdatum',
    telefon: 'Telefonnummer',
    email: 'E-Mail-Adresse',
    lakhely: 'Wohnort / Postleitzahl',
    orszag: 'In welchem Land leben Sie derzeit?',
    bJogositvanyEve: 'Seit wann besitzen Sie den Führerschein Klasse B?',
    professzionalisEv: 'Jahre professionelle Fahrerfahrung',
    soforkentNemetorszag: 'Haben Sie bereits als Profifahrer in Deutschland gearbeitet?',
    korabbiTerulet: 'In welchen Bereichen haben Sie zuvor gearbeitet?',
    premiumTapasztalat: 'Haben Sie Premium- oder Luxusfahrzeuge gefahren?',
    premiumMarkak: 'Mit welchen Premium-/Luxusmarken haben Sie Erfahrung?',
    premiumGyakorisag: 'Wie oft haben Sie Premium- oder Luxusfahrzeuge gefahren?',
    automataValto: 'Erfahrung mit Automatik und leistungsstarken Fahrzeugen?',
    munkavallalasiJog: 'Haben Sie eine gültige Arbeitserlaubnis in Deutschland?',
    nemetorszagiCim: 'Haben Sie eine Meldeadresse in Deutschland?',
    munkabaAllas: 'Wann können Sie anfangen?',
    rugalmassag: 'Wie flexibel sind Sie beim Einsatzort?',
    jogositvanyKategoria: 'Welche Führerscheinklassen besitzen Sie?',
    jogositvanyErvenyes: 'Ist Ihr Führerschein derzeit gültig?',
    eltiltas:
      'Fahrverbot oder schwere Verkehrsverstöße in den letzten 5 Jahren?',
    erkolesi: 'Besitzen Sie ein Führungszeugnis?',
    nemetNyelv: 'Deutschkenntnisse',
    angolNyelv: 'Englischkenntnisse',
    okostelefon: 'Smartphone mit mobilem Internet?',
    navigacio: 'Können Sie Google Maps oder andere Navigations-Apps nutzen?',
    gpsKovetes: 'GPS-Arbeitsverfolgung und digitales System akzeptiert?',
    hosszuUt: 'Bereit für Fahrten von 200–500 km?',
    hetvege: 'Wochenendarbeit möglich?',
    tobbnapos: 'Mehrtägige Einsätze innerhalb Deutschlands?',
    hetiNapok: 'Wie viele Tage pro Woche können Sie arbeiten?',
    haromEvAktiv: 'Mindestens 3 Jahre aktive Fahrerfahrung?',
    haromEvProf: 'Mindestens 3 Jahre professionelle Fahrerfahrung?',
    premiumSzuro: 'Erfahrung mit Premium- oder Luxusfahrzeugen?',
    biztonsagosVezetes: 'Fahren Sie hochwertige Fahrzeuge sicher und verantwortungsvoll?',
    gondosKezeles: 'Behandeln Sie anvertraute Fahrzeuge mit besonderer Sorgfalt?',
    ellenorzesElfogadas:
      'Stimmen Sie der Überprüfung Ihrer Angaben und Dokumente zu?',
    motivacio: 'Warum möchten Sie Premium- und Luxusfahrzeuge in Deutschland fahren?',
    tapasztalatLeiras: 'Kurze Darstellung Ihrer Fahr- und Berufserfahrung.',
  },
  dokumentumokBevezeto: 'Bitte laden Sie die folgenden Dokumente hoch.',
  feltoltes: {
    szemelyi: {
      cim: 'Ausweisdokument',
      leiras: 'Personalausweis oder Reisepass hochladen',
    },
    jogositvany: {
      cim: 'Führerschein',
      leiras: 'Beide Seiten des gültigen Führerscheins hochladen',
    },
    fuehrungszeugnis: {
      cim: 'Führungszeugnis',
      leiras: 'Führungszeugnis hochladen',
      seged: 'Falls noch nicht vorhanden, bitte im Formular angeben.',
    },
    oneletrajz: { cim: 'Lebenslauf', leiras: 'CV / Lebenslauf hochladen' },
    profilkep: {
      cim: 'Profilfoto',
      leiras: 'Aktuelles Profilfoto hochladen',
      seged: 'Nur Bild. Große Dateien werden auf Ausweisgröße optimiert.',
    },
    referencia: {
      cim: 'Referenz / Arbeitgeberbescheinigung',
      leiras: 'Referenz des vorherigen Arbeitgebers oder Beschäftigungsnachweis',
    },
  },
  adatvedelemElotte: 'Ich habe die',
  adatvedelemLink: 'Datenschutzerklärung',
  adatvedelemUtana: ' gelesen und akzeptiere sie.',
  hozzajarulas:
    'Ich willige ein, dass meine Daten und hochgeladenen Dokumente im Auswahlprozess überprüft werden.',
  gombKuldes: 'Bewerbung absenden',
  gombKuldesFut: 'Wird gesendet…',
  gombKepFeldolgozas: 'Bild wird verarbeitet…',
  osszesitoHiba:
    'Bitte füllen Sie alle Pflichtfelder aus und laden Sie die Dokumente hoch.',
  osszesitoHibaDarab: '({n} fehlende Angaben)',
  popupCim: 'Vielen Dank für Ihre Bewerbung!',
  popupSzoveg:
    'Bei erfolgreicher Vorauswahl kontaktieren wir Sie zu den nächsten Schritten.',
  popupZar: 'Schließen',
  valasszon: 'Bitte wählen…',
  egyebPlaceholder: 'Bitte angeben',
  egyebAria: 'Sonstiges — bitte angeben',
  feltoltesGomb: 'Dokument hochladen',
  hibak,
  opciokFelirat: {
    orszagok: [
      'Deutschland',
      'Ungarn',
      'Österreich',
      'Polen',
      'Tschechien',
      'Slowakei',
      'Rumänien',
      'Niederlande',
      'Belgien',
      'Frankreich',
      'Sonstiges',
    ],
    igenNem: ['Ja', 'Nein'],
    bJogositvanyEve: ['Weniger als 1 Jahr', '1–2 Jahre', '3–5 Jahre', 'Mehr als 5 Jahre'],
    professzionalisEv: ['Keine', '1–2 Jahre', '3–5 Jahre', 'Mehr als 5 Jahre'],
    korabbiTerulet: [
      'Personenbeförderung',
      'Fahrzeugüberführung / Fahrzeugübergabe',
      'VIP- oder Luxusbeförderung',
      'Autovermietung',
      'Taxi',
      'Kurier / Zustellung',
      'Sonstiges',
    ],
    premiumMarkak: [
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Porsche',
      'Bentley',
      'Lamborghini',
      'Ferrari',
      'Range Rover',
      'Sonstiges',
    ],
    premiumGyakorisag: ['Gelegentlich', 'Regelmäßig', 'Täglich'],
    munkabaAllas: [
      'Sofort',
      'Innerhalb 1 Woche',
      'Innerhalb 2 Wochen',
      'Innerhalb 1 Monat',
      'Später',
    ],
    rugalmassag: [
      'Nur in meiner Nähe',
      'Flexibel in Deutschland',
      'Bundesweit in Deutschland',
    ],
    jogositvanyKategoria: ['B', 'BE', 'C', 'Sonstiges'],
    erkolesi: ['Ja', 'Nein', 'In Beschaffung'],
    nyelvSzint: ['Gar nicht', 'Grundkenntnisse', 'Kommunikationsniveau', 'Gut', 'Muttersprache'],
    hetvege: ['Ja', 'Nein', 'Gelegentlich'],
    hetiNapok: ['2–3 Tage', '4 Tage', '5 Tage', '6 oder mehr Tage'],
  },
}
