import type { JelentkezesSzovegPaket } from './epit'

const hibak = {
  kotelezo: 'This field is required.',
  valasztas: 'Please select an option.',
  legalabbEgy: 'Please select at least one option.',
  egyeb: 'Please specify your “Other” answer.',
  fajl: 'Document upload is required.',
  email: 'Please enter a valid email address.',
  tizennyolcEv: 'You must be at least 18 years old to apply.',
  adatvedelem: 'You must accept the privacy policy.',
  hozzajarulas: 'Consent is required.',
  fajlPdf: 'Only PDF format is allowed.',
  fajlKep: 'Only image files (JPG, PNG, WebP) are allowed.',
  fajlKepVagyPdf: 'Only image (JPG, PNG, WebP) or PDF is allowed.',
  profilkepFeldolgozas: 'Profile photo processing failed.',
  kuldesSikertelen: 'Submission failed. Please try again.',
}

export const angolJelentkezesPaket: JelentkezesSzovegPaket = {
  seo: {
    cim: 'Driver application | Juliette Logistique',
    leiras:
      'Apply for a premium vehicle transfer driver role with Juliette Logistique in Germany.',
    kulcsszavak: 'driver application, Juliette Logistique, careers, Germany',
  },
  foCim: 'Driver application form',
  alcim: 'Premium and luxury vehicle driver in Germany',
  bevezeto:
    'Please complete this form as accurately as possible. We may verify the information and documents you provide during the selection process.',
  szekcio: {
    szemelyes: '1. Personal details',
    vezetes: '2. Driving experience',
    premium: '3. Premium and luxury vehicle experience',
    nemetorszag: '4. Working in Germany',
    jogositvany: '5. Licence and driving history',
    nyelv: '6. Languages',
    keszsegek: '7. Skills required for the role',
    feltetelek: '8. Employment conditions',
    szurok: '9. Key screening questions',
    dokumentumok: '10. Document upload',
    motivacio: '11. Motivation',
    kuldes: '12. Submit application',
  },
  mezo: {
    teljesNev: 'Full name',
    szuletesiDatum: 'Date of birth',
    telefon: 'Phone number',
    email: 'Email address',
    lakhely: 'City / postal code',
    orszag: 'Which country do you currently live in?',
    bJogositvanyEve: 'How long have you held a category B licence?',
    professzionalisEv: 'Years of professional driving experience',
    soforkentNemetorszag: 'Have you worked as a professional driver in Germany?',
    korabbiTerulet: 'In which areas have you worked before?',
    premiumTapasztalat: 'Have you driven premium or luxury vehicles?',
    premiumMarkak: 'Which premium/luxury brands do you have experience with?',
    premiumGyakorisag: 'How often have you driven premium or luxury vehicles?',
    automataValto: 'Experience with automatic, high-performance vehicles?',
    munkavallalasiJog: 'Do you have valid work authorisation in Germany?',
    nemetorszagiCim: 'Do you have a registered address in Germany?',
    munkabaAllas: 'When can you start?',
    rugalmassag: 'How flexible are you regarding work locations?',
    jogositvanyKategoria: 'Which licence categories do you hold?',
    jogositvanyErvenyes: 'Is your licence currently valid?',
    eltiltas:
      'Any driving ban or serious traffic offence in the last 5 years?',
    erkolesi: 'Do you have a police certificate of good conduct (Führungszeugnis)?',
    nemetNyelv: 'German language level',
    angolNyelv: 'English language level',
    okostelefon: 'Do you have a smartphone with mobile data?',
    navigacio: 'Can you use Google Maps or other navigation apps?',
    gpsKovetes: 'Will you use GPS tracking and our digital work system?',
    hosszuUt: 'Willing to take trips of 200–500 km?',
    hetvege: 'Available to work weekends?',
    tobbnapos: 'Available for multi-day assignments within Germany?',
    hetiNapok: 'How many days per week can you work?',
    haromEvAktiv: 'At least 3 years of active driving experience?',
    haromEvProf: 'At least 3 years of professional driving experience?',
    premiumSzuro: 'Experience driving premium or luxury vehicles?',
    biztonsagosVezetes: 'Do you drive high-value vehicles safely and responsibly?',
    gondosKezeles: 'Will you handle entrusted vehicles with exceptional care?',
    ellenorzesElfogadas:
      'Do you agree that we may verify your experience and documents?',
    motivacio: 'Why do you want to drive premium and luxury cars in Germany?',
    tapasztalatLeiras: 'Briefly describe your driving and professional background.',
  },
  dokumentumokBevezeto: 'Please upload the following documents.',
  feltoltes: {
    szemelyi: {
      cim: 'ID document',
      leiras: 'Upload ID card or passport',
    },
    jogositvany: {
      cim: 'Driving licence',
      leiras: 'Upload both sides of your valid licence',
    },
    fuehrungszeugnis: {
      cim: 'Police certificate / Führungszeugnis',
      leiras: 'Upload your certificate',
      seged: 'If you do not have it yet, please indicate this in the form.',
    },
    oneletrajz: { cim: 'CV / résumé', leiras: 'Upload CV / Lebenslauf' },
    profilkep: {
      cim: 'Profile photo',
      leiras: 'Upload a current profile photo',
      seged: 'Image only. Large files are resized to ID photo dimensions.',
    },
    referencia: {
      cim: 'Reference / employment certificate',
      leiras: 'Reference from a previous employer or proof of employment',
    },
  },
  adatvedelemElotte: 'I have read and accept the',
  adatvedelemLink: 'privacy policy',
  adatvedelemUtana: '.',
  hozzajarulas:
    'I consent to verification of my data and uploaded documents during the selection process.',
  gombKuldes: 'Submit application',
  gombKuldesFut: 'Sending…',
  gombKepFeldolgozas: 'Processing image…',
  osszesitoHiba:
    'Please complete all required fields and upload documents before submitting.',
  osszesitoHibaDarab: '({n} missing items)',
  popupCim: 'Thank you for your application!',
  popupSzoveg:
    'If you pass the initial screening, we will contact you about the next steps.',
  popupZar: 'Close',
  valasszon: 'Select…',
  egyebPlaceholder: 'Please specify',
  egyebAria: 'Other — please specify',
  feltoltesGomb: 'Upload document',
  hibak,
  opciokFelirat: {
    orszagok: [
      'Germany',
      'Hungary',
      'Austria',
      'Poland',
      'Czech Republic',
      'Slovakia',
      'Romania',
      'Netherlands',
      'Belgium',
      'France',
      'Other',
    ],
    igenNem: ['Yes', 'No'],
    bJogositvanyEve: ['Less than 1 year', '1–2 years', '3–5 years', 'More than 5 years'],
    professzionalisEv: ['None', '1–2 years', '3–5 years', 'More than 5 years'],
    korabbiTerulet: [
      'Passenger transport',
      'Vehicle transfer / handover',
      'VIP or luxury passenger transport',
      'Car rental',
      'Taxi',
      'Courier / delivery',
      'Other',
    ],
    premiumMarkak: [
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Porsche',
      'Bentley',
      'Lamborghini',
      'Ferrari',
      'Range Rover',
      'Other',
    ],
    premiumGyakorisag: ['Occasionally', 'Regularly', 'Daily'],
    munkabaAllas: [
      'Immediately',
      'Within 1 week',
      'Within 2 weeks',
      'Within 1 month',
      'Later',
    ],
    rugalmassag: [
      'Near my home only',
      'Flexible within Germany',
      'Nationwide in Germany',
    ],
    jogositvanyKategoria: ['B', 'BE', 'C', 'Other'],
    erkolesi: ['Yes', 'No', 'In progress'],
    nyelvSzint: ['None', 'Basic', 'Conversational', 'Good', 'Native'],
    hetvege: ['Yes', 'No', 'Occasionally'],
    hetiNapok: ['2–3 days', '4 days', '5 days', '6 or more days'],
  },
}
