import type { JelentkezesSzovegPaket } from './epit'
import { EGYEB_ERTEK } from './opciokErtekek'

const hibak = {
  kotelezo: 'Ez a mező kötelező.',
  valasztas: 'Kérjük, válasszon egy lehetőséget.',
  legalabbEgy: 'Válasszon legalább egy lehetőséget.',
  egyeb: 'Kérjük, részletezze az „Egyéb” választ.',
  fajl: 'Dokumentum feltöltése kötelező.',
  email: 'Érvényes e-mail-címet adjon meg.',
  tizennyolcEv:
    'A jelentkezéshez legalább 18 évesnek kell lennie (a 18. életév betöltése kötelező).',
  adatvedelem: 'Az adatvédelmi tájékoztató elfogadása kötelező.',
  hozzajarulas: 'A hozzájárulás megadása kötelező.',
  fajlPdf: 'Csak PDF formátum engedélyezett.',
  fajlKep: 'Csak képfájl (JPG, PNG, WebP) engedélyezett.',
  fajlKepVagyPdf: 'Csak kép (JPG, PNG, WebP) vagy PDF engedélyezett.',
  profilkepFeldolgozas: 'A profilkép feldolgozása sikertelen.',
  kuldesSikertelen: 'A jelentkezés elküldése sikertelen. Próbálja újra.',
}

export const magyarJelentkezesPaket: JelentkezesSzovegPaket = {
  seo: {
    cim: 'Sofőr jelentkezés | Juliette Logistique',
    leiras:
      'Jelentkezzen prémium járműátvezető pozícióra a Juliette Logistique csapatában Németországban.',
    kulcsszavak: 'sofőr jelentkezés, Juliette Logistique, karrier, Németország',
  },
  foCim: 'Sofőr jelentkezési űrlap',
  alcim: 'Németországi prémium- és luxusautó-vezető',
  bevezeto:
    'Kérjük, töltse ki az alábbi űrlapot a lehető legpontosabban. A jelentkezés során megadott adatokat és dokumentumokat a kiválasztási folyamat során ellenőrizhetjük.',
  szekcio: {
    szemelyes: '1. Személyes adatok',
    vezetes: '2. Vezetési tapasztalat',
    premium: '3. Prémium- és luxusautó-tapasztalat',
    nemetorszag: '4. Németországi munkavégzés',
    jogositvany: '5. Jogosítvány és vezetési előélet',
    nyelv: '6. Nyelvtudás',
    keszsegek: '7. Munkavégzéshez szükséges készségek',
    feltetelek: '8. Munkavállalási feltételek',
    szurok: '9. Fontos szűrőkérdések',
    dokumentumok: '10. Dokumentumok feltöltése',
    motivacio: '11. Motiváció',
    kuldes: '12. Jelentkezés elküldése',
  },
  mezo: {
    teljesNev: 'Teljes név',
    szuletesiDatum: 'Születési dátum',
    telefon: 'Telefonszám',
    email: 'E-mail-cím',
    lakhely: 'Lakóhely / irányítószám',
    orszag: 'Melyik országban él jelenleg?',
    bJogositvanyEve: 'Hány éve rendelkezik B kategóriás jogosítvánnyal?',
    professzionalisEv: 'Hány év professzionális vezetési tapasztalattal rendelkezik?',
    soforkentNemetorszag: 'Dolgozott már professzionális sofőrként Németországban?',
    korabbiTerulet: 'Milyen területen dolgozott korábban?',
    premiumTapasztalat: 'Vezetett már prémium vagy luxus kategóriájú járműveket?',
    premiumMarkak: 'Milyen prémium/luxus márkákkal rendelkezik tapasztalattal?',
    premiumGyakorisag: 'Milyen gyakran vezetett prémium vagy luxus járműveket?',
    automataValto:
      'Van tapasztalata automata váltós, nagy teljesítményű járművek vezetésében?',
    munkavallalasiJog:
      'Rendelkezik érvényes munkavállalási jogosultsággal Németországban?',
    nemetorszagiCim: 'Rendelkezik németországi lakcímmel?',
    munkabaAllas: 'Mikor tud munkába állni?',
    rugalmassag: 'Mennyire rugalmas a munkavégzés helyét illetően?',
    jogositvanyKategoria: 'Milyen kategóriájú jogosítvánnyal rendelkezik?',
    jogositvanyErvenyes: 'Érvényes jelenleg a jogosítványa?',
    eltiltas:
      'Volt az elmúlt 5 évben vezetéstől eltiltása vagy súlyos közlekedési szabálysértése?',
    erkolesi: 'Rendelkezik Führungszeugnisszel / erkölcsi bizonyítvánnyal?',
    nemetNyelv: 'Milyen szinten beszél németül?',
    angolNyelv: 'Milyen szinten beszél angolul?',
    okostelefon: 'Rendelkezik okostelefonnal és mobilinternettel?',
    navigacio: 'Tudja használni a Google Maps vagy más navigációs alkalmazásokat?',
    gpsKovetes:
      'Vállalja GPS-alapú munkakövetés és digitális munkarendszer használatát?',
    hosszuUt: 'Hajlandó 200–500 km-es utakat is vállalni?',
    hetvege: 'Vállal hétvégi munkavégzést?',
    tobbnapos: 'Vállal többnapos munkát Németországon belül?',
    hetiNapok: 'Hány napot tud hetente dolgozni?',
    haromEvAktiv: 'Van legalább 3 év aktív vezetési tapasztalata?',
    haromEvProf: 'Van legalább 3 év professzionális vezetési tapasztalata?',
    premiumSzuro: 'Van tapasztalata prémium vagy luxus járművek vezetésében?',
    biztonsagosVezetes:
      'Biztonságosan és felelősségteljesen vezet nagy értékű járműveket?',
    gondosKezeles:
      'Vállalja, hogy a rábízott járműveket kiemelt gondossággal kezeli?',
    ellenorzesElfogadas:
      'Elfogadja, hogy a jelentkezés során vezetési tapasztalatát és dokumentumait ellenőrizhetjük?',
    motivacio: 'Miért szeretne Németországban prémium és luxusautókat vezetni?',
    tapasztalatLeiras:
      'Kérjük, röviden mutassa be korábbi vezetési és szakmai tapasztalatait.',
  },
  dokumentumokBevezeto: 'Kérjük, töltse fel az alábbi dokumentumokat.',
  feltoltes: {
    szemelyi: {
      cim: 'Személyazonosító okmány',
      leiras: 'Személyi igazolvány vagy útlevél feltöltése',
    },
    jogositvany: {
      cim: 'Jogosítvány',
      leiras: 'Érvényes vezetői engedély mindkét oldalának feltöltése',
    },
    fuehrungszeugnis: {
      cim: 'Führungszeugnis / erkölcsi bizonyítvány',
      leiras: 'Führungszeugnis feltöltése',
      seged: 'Ha még nincs, a jelentkezés során jelezze.',
    },
    oneletrajz: { cim: 'Önéletrajz', leiras: 'CV / Lebenslauf feltöltése' },
    profilkep: {
      cim: 'Profilkép',
      leiras: 'Aktuális profilkép feltöltése',
      seged: 'Csak kép. Nagy fájl esetén igazolvány-méretre optimalizáljuk.',
    },
    referencia: {
      cim: 'Referencia / munkáltatói igazolás',
      leiras: 'Korábbi munkáltatói referencia vagy munkaviszony igazolása',
    },
  },
  adatvedelemElotte: 'Elolvastam és elfogadom az',
  adatvedelemLink: 'adatvédelmi tájékoztatót',
  adatvedelemUtana: '.',
  hozzajarulas:
    'Hozzájárulok ahhoz, hogy a jelentkezésemben megadott adatokat és feltöltött dokumentumokat a kiválasztási folyamat során ellenőrizzék.',
  gombKuldes: 'Jelentkezés elküldése',
  gombKuldesFut: 'Küldés…',
  gombKepFeldolgozas: 'Kép feldolgozása…',
  osszesitoHiba:
    'Kérjük, töltse ki az összes kötelező mezőt és töltse fel a dokumentumokat a jelentkezés elküldéséhez.',
  osszesitoHibaDarab: '({n} hiányzó adat)',
  popupCim: 'Köszönjük jelentkezését!',
  popupSzoveg:
    'Sikeres előszűrés esetén felvesszük Önnel a kapcsolatot a további lépésekkel kapcsolatban.',
  popupZar: 'Bezárás',
  valasszon: 'Válasszon…',
  egyebPlaceholder: 'Kérjük, részletezze',
  egyebAria: 'Egyéb megnevezése',
  feltoltesGomb: 'Dokumentum feltöltése',
  hibak,
  opciokFelirat: {
    orszagok: [
      'Németország',
      'Magyarország',
      'Ausztria',
      'Lengyelország',
      'Csehország',
      'Szlovákia',
      'Románia',
      'Hollandia',
      'Belgium',
      'Franciaország',
      EGYEB_ERTEK,
    ],
    igenNem: ['Igen', 'Nem'],
    bJogositvanyEve: ['Kevesebb mint 1 év', '1–2 év', '3–5 év', 'Több mint 5 év'],
    professzionalisEv: ['Nincs', '1–2 év', '3–5 év', 'Több mint 5 év'],
    korabbiTerulet: [
      'Személyszállítás',
      'Fahrzeugüberführung / autóátadás',
      'VIP- vagy luxus személyszállítás',
      'Autókölcsönző',
      'Taxi',
      'Futár / kiszállítás',
      EGYEB_ERTEK,
    ],
    premiumMarkak: [
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Porsche',
      'Bentley',
      'Lamborghini',
      'Ferrari',
      'Range Rover',
      EGYEB_ERTEK,
    ],
    premiumGyakorisag: ['Alkalmanként', 'Rendszeresen', 'Naponta'],
    munkabaAllas: ['Azonnal', '1 héten belül', '2 héten belül', '1 hónapon belül', 'Később'],
    rugalmassag: [
      'Csak a lakóhelyem közelében',
      'Németországon belül rugalmas vagyok',
      'Egész Németországban vállalok munkát',
    ],
    jogositvanyKategoria: ['B', 'BE', 'C', EGYEB_ERTEK],
    erkolesi: ['Igen', 'Nem', 'Beszerzés alatt'],
    nyelvSzint: [
      'Egyáltalán nem',
      'Alapszint',
      'Kommunikációs szint',
      'Jó',
      'Anyanyelvi szint',
    ],
    hetvege: ['Igen', 'Nem', 'Esetenként'],
    hetiNapok: ['2–3 nap', '4 nap', '5 nap', '6 vagy több nap'],
  },
}
